### ISSUE TITLE
HTML Entity Codes

### ISSUE THREAD

**Issue by sdhunt** [JonnyMoore/prj-rev-bwfs-dasmoto#3]
https://github.com/JonnyMoore/prj-rev-bwfs-dasmoto/blob/c83db094f6262215130ea39c9872889cf83f3127/dasmoto/index.html#L12

Although browsers will render a lone ampersand (`&`) verbatim, technically this is malformed HTML and should be corrected. The ampersand character has special meaning in HTML; it marks the beginning of an _HTML entity code_. To properly define an ampersand, use the code `&amp;`

See:
* https://developer.mozilla.org/en-US/docs/Glossary/Entity
* https://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

**Comment by JonnyMoore** [comment]
Noted, thanks!
