### ISSUE TITLE
Prefer class selectors over element selectors

### ISSUE THREAD

**Issue by sdhunt** [JonnyMoore/prj-rev-bwfs-dasmoto#4]
https://github.com/JonnyMoore/prj-rev-bwfs-dasmoto/blob/master/dasmoto/index.html#L19
```
  <p> ... in different sizes. <strong>Starting at $3.00 / brush.</strong></p>
```
While using `<strong>` and corresponding selector `strong { ... }` in the stylesheet gets the job done, consider using a class selector instead:
```
  <p> ... in different sizes. <span class="pricing">Starting at $3.00 / brush.</span></p>
```
```
.pricing {
  font-weight: bold;
  color: blue;
}
```

When you start implementing larger projects you will quickly find that using classes is preferable over element types, as you can name the class to describe "what" is being styled, making the code much more readable.

**Comment by JonnyMoore** [comment]
Ok will do. I thought about it for this project but as there was only one instance of <strong> thought it was unnecessary. Will do this going forward.
