### ISSUE TITLE
CSS Source

### ISSUE THREAD

**Issue by sdhunt** [JonnyMoore/prj-rev-bwfs-dasmoto#5]
Nice work with the stylesheet - it is clear, readable, and follows the common conventions for formatting a CSS file.

Good job remembering to declare multiple selectors for the same rule each on their own line...
https://github.com/JonnyMoore/prj-rev-bwfs-dasmoto/blob/c83db094f6262215130ea39c9872889cf83f3127/dasmoto/resources/css/style.css#L1-L6

In this case, you might consider using the "global" selector (`*`) to define the font-family document-wide:
```
* {
  font-family: "Helvetica", sans-serif;
}
```
The global selector will match _every_ element in the document, so can be useful for applying styles across the whole page.

**Comment by JonnyMoore** [comment]
Awesome thanks!
