### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by sdhunt** [JonnyMoore/prj-rev-bwfs-dasmoto#6]
_Grade:_ **Meets Expectations**

Nice work creating a web page that accurately matches the project specification!

There are a couple of syntax issues to deal with in the HTML (unmatched tags), but this is easily fixed.

Although referencing the images from the web is fine, consider downloading the images to the project directory and referencing them locally; this will keep your project self-contained.

Some further reading:
* https://learn.shayhowe.com/html-css/writing-your-best-code/
* https://css-tricks.com/the-difference-between-id-and-class/

Keep on coding!

**Comment by JonnyMoore** [comment]
Thanks for the feedback. Really great!
